version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  trino:
    image: trinodb/trino:latest
    container_name: trino_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./trino-config:/etc/trino

  streamlit:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: streamlit_app
      restart: always
      ports:
        - "8501:8501"
      depends_on:
        - postgres
        - trino
      volumes:
        - .:/app


volumes:
  postgres_data:
